// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package dashboard

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID) {
		delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
	} else if a.ko.Spec.AWSAccountID != nil && b.ko.Spec.AWSAccountID != nil {
		if *a.ko.Spec.AWSAccountID != *b.ko.Spec.AWSAccountID {
			delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
		}
	}
	if len(a.ko.Spec.FolderARNs) != len(b.ko.Spec.FolderARNs) {
		delta.Add("Spec.FolderARNs", a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs)
	} else if len(a.ko.Spec.FolderARNs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs) {
			delta.Add("Spec.FolderARNs", a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ID, b.ko.Spec.ID) {
		delta.Add("Spec.ID", a.ko.Spec.ID, b.ko.Spec.ID)
	} else if a.ko.Spec.ID != nil && b.ko.Spec.ID != nil {
		if *a.ko.Spec.ID != *b.ko.Spec.ID {
			delta.Add("Spec.ID", a.ko.Spec.ID, b.ko.Spec.ID)
		}
	}
	if len(a.ko.Spec.LinkEntities) != len(b.ko.Spec.LinkEntities) {
		delta.Add("Spec.LinkEntities", a.ko.Spec.LinkEntities, b.ko.Spec.LinkEntities)
	} else if len(a.ko.Spec.LinkEntities) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.LinkEntities, b.ko.Spec.LinkEntities) {
			delta.Add("Spec.LinkEntities", a.ko.Spec.LinkEntities, b.ko.Spec.LinkEntities)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.LinkEntityRefs, b.ko.Spec.LinkEntityRefs) {
		delta.Add("Spec.LinkEntityRefs", a.ko.Spec.LinkEntityRefs, b.ko.Spec.LinkEntityRefs)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Parameters, b.ko.Spec.Parameters) {
		delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
	} else if a.ko.Spec.Parameters != nil && b.ko.Spec.Parameters != nil {
		if len(a.ko.Spec.Parameters.DateTimeParameters) != len(b.ko.Spec.Parameters.DateTimeParameters) {
			delta.Add("Spec.Parameters.DateTimeParameters", a.ko.Spec.Parameters.DateTimeParameters, b.ko.Spec.Parameters.DateTimeParameters)
		} else if len(a.ko.Spec.Parameters.DateTimeParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.DateTimeParameters, b.ko.Spec.Parameters.DateTimeParameters) {
				delta.Add("Spec.Parameters.DateTimeParameters", a.ko.Spec.Parameters.DateTimeParameters, b.ko.Spec.Parameters.DateTimeParameters)
			}
		}
		if len(a.ko.Spec.Parameters.DecimalParameters) != len(b.ko.Spec.Parameters.DecimalParameters) {
			delta.Add("Spec.Parameters.DecimalParameters", a.ko.Spec.Parameters.DecimalParameters, b.ko.Spec.Parameters.DecimalParameters)
		} else if len(a.ko.Spec.Parameters.DecimalParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.DecimalParameters, b.ko.Spec.Parameters.DecimalParameters) {
				delta.Add("Spec.Parameters.DecimalParameters", a.ko.Spec.Parameters.DecimalParameters, b.ko.Spec.Parameters.DecimalParameters)
			}
		}
		if len(a.ko.Spec.Parameters.IntegerParameters) != len(b.ko.Spec.Parameters.IntegerParameters) {
			delta.Add("Spec.Parameters.IntegerParameters", a.ko.Spec.Parameters.IntegerParameters, b.ko.Spec.Parameters.IntegerParameters)
		} else if len(a.ko.Spec.Parameters.IntegerParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.IntegerParameters, b.ko.Spec.Parameters.IntegerParameters) {
				delta.Add("Spec.Parameters.IntegerParameters", a.ko.Spec.Parameters.IntegerParameters, b.ko.Spec.Parameters.IntegerParameters)
			}
		}
		if len(a.ko.Spec.Parameters.StringParameters) != len(b.ko.Spec.Parameters.StringParameters) {
			delta.Add("Spec.Parameters.StringParameters", a.ko.Spec.Parameters.StringParameters, b.ko.Spec.Parameters.StringParameters)
		} else if len(a.ko.Spec.Parameters.StringParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.StringParameters, b.ko.Spec.Parameters.StringParameters) {
				delta.Add("Spec.Parameters.StringParameters", a.ko.Spec.Parameters.StringParameters, b.ko.Spec.Parameters.StringParameters)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions, b.ko.Spec.PublishOptions) {
		delta.Add("Spec.PublishOptions", a.ko.Spec.PublishOptions, b.ko.Spec.PublishOptions)
	} else if a.ko.Spec.PublishOptions != nil && b.ko.Spec.PublishOptions != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.AdHocFilteringOption, b.ko.Spec.PublishOptions.AdHocFilteringOption) {
			delta.Add("Spec.PublishOptions.AdHocFilteringOption", a.ko.Spec.PublishOptions.AdHocFilteringOption, b.ko.Spec.PublishOptions.AdHocFilteringOption)
		} else if a.ko.Spec.PublishOptions.AdHocFilteringOption != nil && b.ko.Spec.PublishOptions.AdHocFilteringOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus, b.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus", a.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus, b.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus", a.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus, b.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.DataPointDrillUpDownOption, b.ko.Spec.PublishOptions.DataPointDrillUpDownOption) {
			delta.Add("Spec.PublishOptions.DataPointDrillUpDownOption", a.ko.Spec.PublishOptions.DataPointDrillUpDownOption, b.ko.Spec.PublishOptions.DataPointDrillUpDownOption)
		} else if a.ko.Spec.PublishOptions.DataPointDrillUpDownOption != nil && b.ko.Spec.PublishOptions.DataPointDrillUpDownOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus", a.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus", a.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.DataPointMenuLabelOption, b.ko.Spec.PublishOptions.DataPointMenuLabelOption) {
			delta.Add("Spec.PublishOptions.DataPointMenuLabelOption", a.ko.Spec.PublishOptions.DataPointMenuLabelOption, b.ko.Spec.PublishOptions.DataPointMenuLabelOption)
		} else if a.ko.Spec.PublishOptions.DataPointMenuLabelOption != nil && b.ko.Spec.PublishOptions.DataPointMenuLabelOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus", a.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus", a.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.DataPointTooltipOption, b.ko.Spec.PublishOptions.DataPointTooltipOption) {
			delta.Add("Spec.PublishOptions.DataPointTooltipOption", a.ko.Spec.PublishOptions.DataPointTooltipOption, b.ko.Spec.PublishOptions.DataPointTooltipOption)
		} else if a.ko.Spec.PublishOptions.DataPointTooltipOption != nil && b.ko.Spec.PublishOptions.DataPointTooltipOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus", a.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus", a.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.DataQAEnabledOption, b.ko.Spec.PublishOptions.DataQAEnabledOption) {
			delta.Add("Spec.PublishOptions.DataQAEnabledOption", a.ko.Spec.PublishOptions.DataQAEnabledOption, b.ko.Spec.PublishOptions.DataQAEnabledOption)
		} else if a.ko.Spec.PublishOptions.DataQAEnabledOption != nil && b.ko.Spec.PublishOptions.DataQAEnabledOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus", a.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus", a.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.DataStoriesSharingOption, b.ko.Spec.PublishOptions.DataStoriesSharingOption) {
			delta.Add("Spec.PublishOptions.DataStoriesSharingOption", a.ko.Spec.PublishOptions.DataStoriesSharingOption, b.ko.Spec.PublishOptions.DataStoriesSharingOption)
		} else if a.ko.Spec.PublishOptions.DataStoriesSharingOption != nil && b.ko.Spec.PublishOptions.DataStoriesSharingOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus", a.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus", a.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus, b.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.ExecutiveSummaryOption, b.ko.Spec.PublishOptions.ExecutiveSummaryOption) {
			delta.Add("Spec.PublishOptions.ExecutiveSummaryOption", a.ko.Spec.PublishOptions.ExecutiveSummaryOption, b.ko.Spec.PublishOptions.ExecutiveSummaryOption)
		} else if a.ko.Spec.PublishOptions.ExecutiveSummaryOption != nil && b.ko.Spec.PublishOptions.ExecutiveSummaryOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus, b.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus", a.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus, b.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus", a.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus, b.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.ExportToCSVOption, b.ko.Spec.PublishOptions.ExportToCSVOption) {
			delta.Add("Spec.PublishOptions.ExportToCSVOption", a.ko.Spec.PublishOptions.ExportToCSVOption, b.ko.Spec.PublishOptions.ExportToCSVOption)
		} else if a.ko.Spec.PublishOptions.ExportToCSVOption != nil && b.ko.Spec.PublishOptions.ExportToCSVOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus, b.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus", a.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus, b.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus", a.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus, b.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption, b.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption) {
			delta.Add("Spec.PublishOptions.ExportWithHiddenFieldsOption", a.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption, b.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption)
		} else if a.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption != nil && b.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus", a.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus", a.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.QuickSuiteActionsOption, b.ko.Spec.PublishOptions.QuickSuiteActionsOption) {
			delta.Add("Spec.PublishOptions.QuickSuiteActionsOption", a.ko.Spec.PublishOptions.QuickSuiteActionsOption, b.ko.Spec.PublishOptions.QuickSuiteActionsOption)
		} else if a.ko.Spec.PublishOptions.QuickSuiteActionsOption != nil && b.ko.Spec.PublishOptions.QuickSuiteActionsOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus, b.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus", a.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus, b.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus", a.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus, b.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.SheetControlsOption, b.ko.Spec.PublishOptions.SheetControlsOption) {
			delta.Add("Spec.PublishOptions.SheetControlsOption", a.ko.Spec.PublishOptions.SheetControlsOption, b.ko.Spec.PublishOptions.SheetControlsOption)
		} else if a.ko.Spec.PublishOptions.SheetControlsOption != nil && b.ko.Spec.PublishOptions.SheetControlsOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState, b.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState) {
				delta.Add("Spec.PublishOptions.SheetControlsOption.VisibilityState", a.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState, b.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState)
			} else if a.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState != nil && b.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState != nil {
				if *a.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState != *b.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState {
					delta.Add("Spec.PublishOptions.SheetControlsOption.VisibilityState", a.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState, b.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption, b.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption) {
			delta.Add("Spec.PublishOptions.SheetLayoutElementMaximizationOption", a.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption, b.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption)
		} else if a.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption != nil && b.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus, b.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus", a.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus, b.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus", a.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus, b.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.VisualAxisSortOption, b.ko.Spec.PublishOptions.VisualAxisSortOption) {
			delta.Add("Spec.PublishOptions.VisualAxisSortOption", a.ko.Spec.PublishOptions.VisualAxisSortOption, b.ko.Spec.PublishOptions.VisualAxisSortOption)
		} else if a.ko.Spec.PublishOptions.VisualAxisSortOption != nil && b.ko.Spec.PublishOptions.VisualAxisSortOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus, b.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus", a.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus, b.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus", a.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus, b.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.VisualMenuOption, b.ko.Spec.PublishOptions.VisualMenuOption) {
			delta.Add("Spec.PublishOptions.VisualMenuOption", a.ko.Spec.PublishOptions.VisualMenuOption, b.ko.Spec.PublishOptions.VisualMenuOption)
		} else if a.ko.Spec.PublishOptions.VisualMenuOption != nil && b.ko.Spec.PublishOptions.VisualMenuOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus, b.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus) {
				delta.Add("Spec.PublishOptions.VisualMenuOption.AvailabilityStatus", a.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus, b.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus)
			} else if a.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus != nil {
				if *a.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus {
					delta.Add("Spec.PublishOptions.VisualMenuOption.AvailabilityStatus", a.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus, b.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.VisualPublishOptions, b.ko.Spec.PublishOptions.VisualPublishOptions) {
			delta.Add("Spec.PublishOptions.VisualPublishOptions", a.ko.Spec.PublishOptions.VisualPublishOptions, b.ko.Spec.PublishOptions.VisualPublishOptions)
		} else if a.ko.Spec.PublishOptions.VisualPublishOptions != nil && b.ko.Spec.PublishOptions.VisualPublishOptions != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption, b.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption) {
				delta.Add("Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption", a.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption, b.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption)
			} else if a.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption != nil && b.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus) {
					delta.Add("Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus", a.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus)
				} else if a.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus != nil && b.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus != nil {
					if *a.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus != *b.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus {
						delta.Add("Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus", a.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus)
					}
				}
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ThemeARN, b.ko.Spec.ThemeARN) {
		delta.Add("Spec.ThemeARN", a.ko.Spec.ThemeARN, b.ko.Spec.ThemeARN)
	} else if a.ko.Spec.ThemeARN != nil && b.ko.Spec.ThemeARN != nil {
		if *a.ko.Spec.ThemeARN != *b.ko.Spec.ThemeARN {
			delta.Add("Spec.ThemeARN", a.ko.Spec.ThemeARN, b.ko.Spec.ThemeARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ValidationStrategy, b.ko.Spec.ValidationStrategy) {
		delta.Add("Spec.ValidationStrategy", a.ko.Spec.ValidationStrategy, b.ko.Spec.ValidationStrategy)
	} else if a.ko.Spec.ValidationStrategy != nil && b.ko.Spec.ValidationStrategy != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.ValidationStrategy.Mode, b.ko.Spec.ValidationStrategy.Mode) {
			delta.Add("Spec.ValidationStrategy.Mode", a.ko.Spec.ValidationStrategy.Mode, b.ko.Spec.ValidationStrategy.Mode)
		} else if a.ko.Spec.ValidationStrategy.Mode != nil && b.ko.Spec.ValidationStrategy.Mode != nil {
			if *a.ko.Spec.ValidationStrategy.Mode != *b.ko.Spec.ValidationStrategy.Mode {
				delta.Add("Spec.ValidationStrategy.Mode", a.ko.Spec.ValidationStrategy.Mode, b.ko.Spec.ValidationStrategy.Mode)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.VersionDescription, b.ko.Spec.VersionDescription) {
		delta.Add("Spec.VersionDescription", a.ko.Spec.VersionDescription, b.ko.Spec.VersionDescription)
	} else if a.ko.Spec.VersionDescription != nil && b.ko.Spec.VersionDescription != nil {
		if *a.ko.Spec.VersionDescription != *b.ko.Spec.VersionDescription {
			delta.Add("Spec.VersionDescription", a.ko.Spec.VersionDescription, b.ko.Spec.VersionDescription)
		}
	}

	if !equality.Semantic.DeepEqual(a.ko.Status.VersionNumber, b.ko.Status.VersionNumber) {
		delta.Add("Status.VersionNumber", a.ko.Status.VersionNumber, b.ko.Status.VersionNumber)
	}
	// Custom SourceEntity comparison. The generated delta skips this field
	// (compare.is_ignored) because DescribeDashboard returns SourceEntityArn
	// with a /version/N suffix.
	if ackcompare.HasNilDifference(a.ko.Spec.SourceEntity, b.ko.Spec.SourceEntity) {
		delta.Add("Spec.SourceEntity", a.ko.Spec.SourceEntity, b.ko.Spec.SourceEntity)
	} else if a.ko.Spec.SourceEntity != nil && b.ko.Spec.SourceEntity != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.SourceEntity.SourceTemplate, b.ko.Spec.SourceEntity.SourceTemplate) {
			delta.Add("Spec.SourceEntity.SourceTemplate", a.ko.Spec.SourceEntity.SourceTemplate, b.ko.Spec.SourceEntity.SourceTemplate)
		} else if a.ko.Spec.SourceEntity.SourceTemplate != nil && b.ko.Spec.SourceEntity.SourceTemplate != nil {
			aARN := a.ko.Spec.SourceEntity.SourceTemplate.ARN
			bARN := b.ko.Spec.SourceEntity.SourceTemplate.ARN
			if ackcompare.HasNilDifference(aARN, bARN) {
				delta.Add("Spec.SourceEntity.SourceTemplate.ARN", aARN, bARN)
			} else if aARN != nil && bARN != nil && !sourceEntityARNsMatch(*aARN, *bARN) {
				delta.Add("Spec.SourceEntity.SourceTemplate.ARN", aARN, bARN)
			}
			if !equality.Semantic.DeepEqual(a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences, b.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences) {
				delta.Add("Spec.SourceEntity.SourceTemplate.DataSetReferences", a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences, b.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences)
			}
		}
	}
	// Custom Permissions comparison using principal-keyed diff.
	if !permissionsEqual(a.ko.Spec.Permissions, b.ko.Spec.Permissions) {
		delta.Add("Spec.Permissions", a.ko.Spec.Permissions, b.ko.Spec.Permissions)
	}
	// Custom LinkSharingConfiguration comparison.
	if ackcompare.HasNilDifference(a.ko.Spec.LinkSharingConfiguration, b.ko.Spec.LinkSharingConfiguration) {
		delta.Add("Spec.LinkSharingConfiguration", a.ko.Spec.LinkSharingConfiguration, b.ko.Spec.LinkSharingConfiguration)
	} else if a.ko.Spec.LinkSharingConfiguration != nil && b.ko.Spec.LinkSharingConfiguration != nil {
		if !permissionsEqual(a.ko.Spec.LinkSharingConfiguration.Permissions, b.ko.Spec.LinkSharingConfiguration.Permissions) {
			delta.Add("Spec.LinkSharingConfiguration.Permissions", a.ko.Spec.LinkSharingConfiguration.Permissions, b.ko.Spec.LinkSharingConfiguration.Permissions)
		}
	}

	return delta
}
