// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package dashboard

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/quicksight"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/quicksight/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/quicksight-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Dashboard{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeDashboardOutput
	resp, err = rm.sdkapi.DescribeDashboard(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeDashboard", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Dashboard.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Dashboard.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Dashboard.CreatedTime != nil {
		ko.Status.CreatedTime = &metav1.Time{*resp.Dashboard.CreatedTime}
	} else {
		ko.Status.CreatedTime = nil
	}
	if resp.Dashboard.DashboardId != nil {
		ko.Spec.ID = resp.Dashboard.DashboardId
	} else {
		ko.Spec.ID = nil
	}
	if resp.Dashboard.LastPublishedTime != nil {
		ko.Status.LastPublishedTime = &metav1.Time{*resp.Dashboard.LastPublishedTime}
	} else {
		ko.Status.LastPublishedTime = nil
	}
	if resp.Dashboard.LastUpdatedTime != nil {
		ko.Status.LastUpdatedTime = &metav1.Time{*resp.Dashboard.LastUpdatedTime}
	} else {
		ko.Status.LastUpdatedTime = nil
	}
	if resp.Dashboard.LinkEntities != nil {
		ko.Spec.LinkEntities = aws.StringSlice(resp.Dashboard.LinkEntities)
	} else {
		ko.Spec.LinkEntities = nil
	}
	if resp.Dashboard.Name != nil {
		ko.Spec.Name = resp.Dashboard.Name
	} else {
		ko.Spec.Name = nil
	}

	rm.setStatusDefaults(ko)
	if resp.Dashboard.Version != nil {
		if resp.Dashboard.Version.VersionNumber != nil {
			ko.Status.VersionNumber = resp.Dashboard.Version.VersionNumber
		}
		if resp.Dashboard.Version.Status != "" {
			ko.Status.VersionStatus = aws.String(string(resp.Dashboard.Version.Status))
		}
		if resp.Dashboard.Version.ThemeArn != nil {
			ko.Spec.ThemeARN = resp.Dashboard.Version.ThemeArn
		}
		if resp.Dashboard.Version.Description != nil {
			ko.Spec.VersionDescription = resp.Dashboard.Version.Description
		}
		if resp.Dashboard.Version.SourceEntityArn != nil {
			placeholderByARN := resolveDataSetPlaceholders(
				ctx, rm.sdkapi, rm.metrics,
				ko.Spec.AWSAccountID,
				*resp.Dashboard.Version.SourceEntityArn,
				resp.Dashboard.Version.DataSetArns,
			)
			var dataSetRefs []*svcapitypes.DataSetReference
			for _, dsARN := range resp.Dashboard.Version.DataSetArns {
				ref := &svcapitypes.DataSetReference{
					DataSetARN: aws.String(dsARN),
				}
				if placeholder, ok := placeholderByARN[dsARN]; ok {
					ref.DataSetPlaceholder = aws.String(placeholder)
				}
				dataSetRefs = append(dataSetRefs, ref)
			}
			ko.Spec.SourceEntity = &svcapitypes.DashboardSourceEntity{
				SourceTemplate: &svcapitypes.DashboardSourceTemplate{
					ARN:               resp.Dashboard.Version.SourceEntityArn,
					DataSetReferences: dataSetRefs,
				},
			}
		}
	}
	// Fetch permissions and link sharing configuration
	perms, lsc, permErr := getDashboardPermissions(
		ctx, rm.sdkapi, rm.metrics,
		ko.Spec.AWSAccountID, ko.Spec.ID,
	)
	if permErr == nil {
		ko.Spec.Permissions = perms
		ko.Spec.LinkSharingConfiguration = lsc
	}
	ko.Spec.Tags, err = getTags(ctx, string(*ko.Status.ACKResourceMetadata.ARN), rm.sdkapi, rm.metrics)
	if err != nil {
		return &resource{ko}, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.AWSAccountID == nil || r.ko.Spec.ID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeDashboardInput, error) {
	res := &svcsdk.DescribeDashboardInput{}

	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}
	if r.ko.Spec.ID != nil {
		res.DashboardId = r.ko.Spec.ID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateDashboardOutput
	_ = resp
	resp, err = rm.sdkapi.CreateDashboard(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateDashboard", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CreationStatus != "" {
		ko.Status.CreationStatus = aws.String(string(resp.CreationStatus))
	} else {
		ko.Status.CreationStatus = nil
	}
	if resp.DashboardId != nil {
		ko.Spec.ID = resp.DashboardId
	} else {
		ko.Spec.ID = nil
	}
	if resp.VersionArn != nil {
		ko.Status.VersionARN = resp.VersionArn
	} else {
		ko.Status.VersionARN = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateDashboardInput, error) {
	res := &svcsdk.CreateDashboardInput{}

	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}
	if r.ko.Spec.ID != nil {
		res.DashboardId = r.ko.Spec.ID
	}
	if r.ko.Spec.PublishOptions != nil {
		f2 := &svcsdktypes.DashboardPublishOptions{}
		if r.ko.Spec.PublishOptions.AdHocFilteringOption != nil {
			f2f0 := &svcsdktypes.AdHocFilteringOption{}
			if r.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus != nil {
				f2f0.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus)
			}
			f2.AdHocFilteringOption = f2f0
		}
		if r.ko.Spec.PublishOptions.DataPointDrillUpDownOption != nil {
			f2f1 := &svcsdktypes.DataPointDrillUpDownOption{}
			if r.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus != nil {
				f2f1.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus)
			}
			f2.DataPointDrillUpDownOption = f2f1
		}
		if r.ko.Spec.PublishOptions.DataPointMenuLabelOption != nil {
			f2f2 := &svcsdktypes.DataPointMenuLabelOption{}
			if r.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus != nil {
				f2f2.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus)
			}
			f2.DataPointMenuLabelOption = f2f2
		}
		if r.ko.Spec.PublishOptions.DataPointTooltipOption != nil {
			f2f3 := &svcsdktypes.DataPointTooltipOption{}
			if r.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus != nil {
				f2f3.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus)
			}
			f2.DataPointTooltipOption = f2f3
		}
		if r.ko.Spec.PublishOptions.DataQAEnabledOption != nil {
			f2f4 := &svcsdktypes.DataQAEnabledOption{}
			if r.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus != nil {
				f2f4.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus)
			}
			f2.DataQAEnabledOption = f2f4
		}
		if r.ko.Spec.PublishOptions.DataStoriesSharingOption != nil {
			f2f5 := &svcsdktypes.DataStoriesSharingOption{}
			if r.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus != nil {
				f2f5.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus)
			}
			f2.DataStoriesSharingOption = f2f5
		}
		if r.ko.Spec.PublishOptions.ExecutiveSummaryOption != nil {
			f2f6 := &svcsdktypes.ExecutiveSummaryOption{}
			if r.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus != nil {
				f2f6.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus)
			}
			f2.ExecutiveSummaryOption = f2f6
		}
		if r.ko.Spec.PublishOptions.ExportToCSVOption != nil {
			f2f7 := &svcsdktypes.ExportToCSVOption{}
			if r.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus != nil {
				f2f7.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus)
			}
			f2.ExportToCSVOption = f2f7
		}
		if r.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption != nil {
			f2f8 := &svcsdktypes.ExportWithHiddenFieldsOption{}
			if r.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus != nil {
				f2f8.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus)
			}
			f2.ExportWithHiddenFieldsOption = f2f8
		}
		if r.ko.Spec.PublishOptions.QuickSuiteActionsOption != nil {
			f2f9 := &svcsdktypes.QuickSuiteActionsOption{}
			if r.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus != nil {
				f2f9.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus)
			}
			f2.QuickSuiteActionsOption = f2f9
		}
		if r.ko.Spec.PublishOptions.SheetControlsOption != nil {
			f2f10 := &svcsdktypes.SheetControlsOption{}
			if r.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState != nil {
				f2f10.VisibilityState = svcsdktypes.DashboardUIState(*r.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState)
			}
			f2.SheetControlsOption = f2f10
		}
		if r.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption != nil {
			f2f11 := &svcsdktypes.SheetLayoutElementMaximizationOption{}
			if r.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus != nil {
				f2f11.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus)
			}
			f2.SheetLayoutElementMaximizationOption = f2f11
		}
		if r.ko.Spec.PublishOptions.VisualAxisSortOption != nil {
			f2f12 := &svcsdktypes.VisualAxisSortOption{}
			if r.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus != nil {
				f2f12.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus)
			}
			f2.VisualAxisSortOption = f2f12
		}
		if r.ko.Spec.PublishOptions.VisualMenuOption != nil {
			f2f13 := &svcsdktypes.VisualMenuOption{}
			if r.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus != nil {
				f2f13.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus)
			}
			f2.VisualMenuOption = f2f13
		}
		if r.ko.Spec.PublishOptions.VisualPublishOptions != nil {
			f2f14 := &svcsdktypes.DashboardVisualPublishOptions{}
			if r.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption != nil {
				f2f14f0 := &svcsdktypes.ExportHiddenFieldsOption{}
				if r.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus != nil {
					f2f14f0.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus)
				}
				f2f14.ExportHiddenFieldsOption = f2f14f0
			}
			f2.VisualPublishOptions = f2f14
		}
		res.DashboardPublishOptions = f2
	}
	if r.ko.Spec.FolderARNs != nil {
		res.FolderArns = aws.ToStringSlice(r.ko.Spec.FolderARNs)
	}
	if r.ko.Spec.LinkEntities != nil {
		res.LinkEntities = aws.ToStringSlice(r.ko.Spec.LinkEntities)
	}
	if r.ko.Spec.LinkSharingConfiguration != nil {
		f5 := &svcsdktypes.LinkSharingConfiguration{}
		if r.ko.Spec.LinkSharingConfiguration.Permissions != nil {
			f5f0 := []svcsdktypes.ResourcePermission{}
			for _, f5f0iter := range r.ko.Spec.LinkSharingConfiguration.Permissions {
				f5f0elem := &svcsdktypes.ResourcePermission{}
				if f5f0iter.Actions != nil {
					f5f0elem.Actions = aws.ToStringSlice(f5f0iter.Actions)
				}
				if f5f0iter.Principal != nil {
					f5f0elem.Principal = f5f0iter.Principal
				}
				f5f0 = append(f5f0, *f5f0elem)
			}
			f5.Permissions = f5f0
		}
		res.LinkSharingConfiguration = f5
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Parameters != nil {
		f7 := &svcsdktypes.Parameters{}
		if r.ko.Spec.Parameters.DateTimeParameters != nil {
			f7f0 := []svcsdktypes.DateTimeParameter{}
			for _, f7f0iter := range r.ko.Spec.Parameters.DateTimeParameters {
				f7f0elem := &svcsdktypes.DateTimeParameter{}
				if f7f0iter.Name != nil {
					f7f0elem.Name = f7f0iter.Name
				}
				if f7f0iter.Values != nil {
					f7f0elemf1 := []time.Time{}
					for _, f7f0elemf1iter := range f7f0iter.Values {
						var f7f0elemf1elem time.Time
						f7f0elemf1elem = f7f0elemf1iter.Time
						f7f0elemf1 = append(f7f0elemf1, f7f0elemf1elem)
					}
					f7f0elem.Values = f7f0elemf1
				}
				f7f0 = append(f7f0, *f7f0elem)
			}
			f7.DateTimeParameters = f7f0
		}
		if r.ko.Spec.Parameters.DecimalParameters != nil {
			f7f1 := []svcsdktypes.DecimalParameter{}
			for _, f7f1iter := range r.ko.Spec.Parameters.DecimalParameters {
				f7f1elem := &svcsdktypes.DecimalParameter{}
				if f7f1iter.Name != nil {
					f7f1elem.Name = f7f1iter.Name
				}
				if f7f1iter.Values != nil {
					f7f1elemf1 := []float64{}
					for _, f7f1elemf1iter := range f7f1iter.Values {
						var f7f1elemf1elem float64
						f7f1elemf1elem = *f7f1elemf1iter
						f7f1elemf1 = append(f7f1elemf1, f7f1elemf1elem)
					}
					f7f1elem.Values = f7f1elemf1
				}
				f7f1 = append(f7f1, *f7f1elem)
			}
			f7.DecimalParameters = f7f1
		}
		if r.ko.Spec.Parameters.IntegerParameters != nil {
			f7f2 := []svcsdktypes.IntegerParameter{}
			for _, f7f2iter := range r.ko.Spec.Parameters.IntegerParameters {
				f7f2elem := &svcsdktypes.IntegerParameter{}
				if f7f2iter.Name != nil {
					f7f2elem.Name = f7f2iter.Name
				}
				if f7f2iter.Values != nil {
					f7f2elem.Values = aws.ToInt64Slice(f7f2iter.Values)
				}
				f7f2 = append(f7f2, *f7f2elem)
			}
			f7.IntegerParameters = f7f2
		}
		if r.ko.Spec.Parameters.StringParameters != nil {
			f7f3 := []svcsdktypes.StringParameter{}
			for _, f7f3iter := range r.ko.Spec.Parameters.StringParameters {
				f7f3elem := &svcsdktypes.StringParameter{}
				if f7f3iter.Name != nil {
					f7f3elem.Name = f7f3iter.Name
				}
				if f7f3iter.Values != nil {
					f7f3elem.Values = aws.ToStringSlice(f7f3iter.Values)
				}
				f7f3 = append(f7f3, *f7f3elem)
			}
			f7.StringParameters = f7f3
		}
		res.Parameters = f7
	}
	if r.ko.Spec.Permissions != nil {
		f8 := []svcsdktypes.ResourcePermission{}
		for _, f8iter := range r.ko.Spec.Permissions {
			f8elem := &svcsdktypes.ResourcePermission{}
			if f8iter.Actions != nil {
				f8elem.Actions = aws.ToStringSlice(f8iter.Actions)
			}
			if f8iter.Principal != nil {
				f8elem.Principal = f8iter.Principal
			}
			f8 = append(f8, *f8elem)
		}
		res.Permissions = f8
	}
	if r.ko.Spec.SourceEntity != nil {
		f9 := &svcsdktypes.DashboardSourceEntity{}
		if r.ko.Spec.SourceEntity.SourceTemplate != nil {
			f9f0 := &svcsdktypes.DashboardSourceTemplate{}
			if r.ko.Spec.SourceEntity.SourceTemplate.ARN != nil {
				f9f0.Arn = r.ko.Spec.SourceEntity.SourceTemplate.ARN
			}
			if r.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences != nil {
				f9f0f1 := []svcsdktypes.DataSetReference{}
				for _, f9f0f1iter := range r.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences {
					f9f0f1elem := &svcsdktypes.DataSetReference{}
					if f9f0f1iter.DataSetARN != nil {
						f9f0f1elem.DataSetArn = f9f0f1iter.DataSetARN
					}
					if f9f0f1iter.DataSetPlaceholder != nil {
						f9f0f1elem.DataSetPlaceholder = f9f0f1iter.DataSetPlaceholder
					}
					f9f0f1 = append(f9f0f1, *f9f0f1elem)
				}
				f9f0.DataSetReferences = f9f0f1
			}
			f9.SourceTemplate = f9f0
		}
		res.SourceEntity = f9
	}
	if r.ko.Spec.Tags != nil {
		f10 := []svcsdktypes.Tag{}
		for _, f10iter := range r.ko.Spec.Tags {
			f10elem := &svcsdktypes.Tag{}
			if f10iter.Key != nil {
				f10elem.Key = f10iter.Key
			}
			if f10iter.Value != nil {
				f10elem.Value = f10iter.Value
			}
			f10 = append(f10, *f10elem)
		}
		res.Tags = f10
	}
	if r.ko.Spec.ThemeARN != nil {
		res.ThemeArn = r.ko.Spec.ThemeARN
	}
	if r.ko.Spec.ValidationStrategy != nil {
		f12 := &svcsdktypes.ValidationStrategy{}
		if r.ko.Spec.ValidationStrategy.Mode != nil {
			f12.Mode = svcsdktypes.ValidationStrategyMode(*r.ko.Spec.ValidationStrategy.Mode)
		}
		res.ValidationStrategy = f12
	}
	if r.ko.Spec.VersionDescription != nil {
		res.VersionDescription = r.ko.Spec.VersionDescription
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	// A VersionNumber diff means UpdateDashboard created a new draft version.
	// We must publish it before updating Status.VersionNumber on the desired
	// resource. If we set VersionNumber before a successful publish, a
	// subsequent reconcile would see no diff and skip the publish, leaving
	// the dashboard stuck on the old published version.
	if delta.DifferentAt("Status.VersionNumber") {
		ready, versionStatus := dashboardVersionReady(ctx, rm.sdkapi, rm.metrics, desired, desired.ko.Status.VersionNumber)
		if !ready {
			return desired, requeueWaitVersionReady(desired)
		}
		_, pubErr := rm.sdkapi.UpdateDashboardPublishedVersion(ctx, &svcsdk.UpdateDashboardPublishedVersionInput{
			AwsAccountId:  desired.ko.Spec.AWSAccountID,
			DashboardId:   desired.ko.Spec.ID,
			VersionNumber: desired.ko.Status.VersionNumber,
		})
		rm.metrics.RecordAPICall("UPDATE", "UpdateDashboardPublishedVersion", pubErr)
		if pubErr != nil {
			return desired, pubErr
		}
		// VersionNumber is already correct on desired. Set VersionStatus
		// from the DescribeDashboard result for the desired version.
		desired.ko.Status.VersionStatus = &versionStatus
	}
	if delta.DifferentAt("Spec.Tags") {
		arn := string(*latest.ko.Status.ACKResourceMetadata.ARN)
		err = syncTags(
			ctx,
			desired.ko.Spec.Tags, latest.ko.Spec.Tags,
			&arn, convertToOrderedACKTags, rm.sdkapi, rm.metrics,
		)
		if err != nil {
			return desired, err
		}
	}
	if delta.DifferentAt("Spec.Permissions") || delta.DifferentAt("Spec.LinkSharingConfiguration") {
		err = syncPermissions(
			ctx, rm.sdkapi, rm.metrics,
			desired.ko.Spec.AWSAccountID,
			desired.ko.Spec.ID,
			desired.ko.Spec.Permissions,
			latest.ko.Spec.Permissions,
			desired.ko.Spec.LinkSharingConfiguration,
			latest.ko.Spec.LinkSharingConfiguration,
		)
		if err != nil {
			return desired, err
		}
	}
	if delta.DifferentAt("Spec.LinkEntities") {
		err = syncLinkEntities(
			ctx, rm.sdkapi, rm.metrics,
			desired.ko.Spec.AWSAccountID,
			desired.ko.Spec.ID,
			desired.ko.Spec.LinkEntities,
		)
		if err != nil {
			return desired, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags", "Spec.Permissions", "Spec.LinkSharingConfiguration", "Spec.LinkEntities", "Status.VersionNumber") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateDashboardOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateDashboard(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateDashboard", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CreationStatus != "" {
		ko.Status.CreationStatus = aws.String(string(resp.CreationStatus))
	} else {
		ko.Status.CreationStatus = nil
	}
	if resp.DashboardId != nil {
		ko.Spec.ID = resp.DashboardId
	} else {
		ko.Spec.ID = nil
	}
	if resp.VersionArn != nil {
		ko.Status.VersionARN = resp.VersionArn
	} else {
		ko.Status.VersionARN = nil
	}

	rm.setStatusDefaults(ko)
	if resp.CreationStatus != "" {
		ko.Status.VersionStatus = aws.String(string(resp.CreationStatus))
	}
	if resp.VersionArn != nil {
		// VersionArn format: arn:aws:quicksight:<region>:<account>:dashboard/<id>/version/<number>
		parts := strings.Split(*resp.VersionArn, "/version/")
		if len(parts) == 2 {
			var vn int64
			if _, scanErr := fmt.Sscanf(parts[1], "%d", &vn); scanErr == nil {
				ko.Status.VersionNumber = &vn
			}
		}
	}

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateDashboardInput, error) {
	res := &svcsdk.UpdateDashboardInput{}

	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}
	if r.ko.Spec.ID != nil {
		res.DashboardId = r.ko.Spec.ID
	}
	if r.ko.Spec.PublishOptions != nil {
		f2 := &svcsdktypes.DashboardPublishOptions{}
		if r.ko.Spec.PublishOptions.AdHocFilteringOption != nil {
			f2f0 := &svcsdktypes.AdHocFilteringOption{}
			if r.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus != nil {
				f2f0.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.AdHocFilteringOption.AvailabilityStatus)
			}
			f2.AdHocFilteringOption = f2f0
		}
		if r.ko.Spec.PublishOptions.DataPointDrillUpDownOption != nil {
			f2f1 := &svcsdktypes.DataPointDrillUpDownOption{}
			if r.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus != nil {
				f2f1.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.DataPointDrillUpDownOption.AvailabilityStatus)
			}
			f2.DataPointDrillUpDownOption = f2f1
		}
		if r.ko.Spec.PublishOptions.DataPointMenuLabelOption != nil {
			f2f2 := &svcsdktypes.DataPointMenuLabelOption{}
			if r.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus != nil {
				f2f2.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.DataPointMenuLabelOption.AvailabilityStatus)
			}
			f2.DataPointMenuLabelOption = f2f2
		}
		if r.ko.Spec.PublishOptions.DataPointTooltipOption != nil {
			f2f3 := &svcsdktypes.DataPointTooltipOption{}
			if r.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus != nil {
				f2f3.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.DataPointTooltipOption.AvailabilityStatus)
			}
			f2.DataPointTooltipOption = f2f3
		}
		if r.ko.Spec.PublishOptions.DataQAEnabledOption != nil {
			f2f4 := &svcsdktypes.DataQAEnabledOption{}
			if r.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus != nil {
				f2f4.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.DataQAEnabledOption.AvailabilityStatus)
			}
			f2.DataQAEnabledOption = f2f4
		}
		if r.ko.Spec.PublishOptions.DataStoriesSharingOption != nil {
			f2f5 := &svcsdktypes.DataStoriesSharingOption{}
			if r.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus != nil {
				f2f5.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.DataStoriesSharingOption.AvailabilityStatus)
			}
			f2.DataStoriesSharingOption = f2f5
		}
		if r.ko.Spec.PublishOptions.ExecutiveSummaryOption != nil {
			f2f6 := &svcsdktypes.ExecutiveSummaryOption{}
			if r.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus != nil {
				f2f6.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.ExecutiveSummaryOption.AvailabilityStatus)
			}
			f2.ExecutiveSummaryOption = f2f6
		}
		if r.ko.Spec.PublishOptions.ExportToCSVOption != nil {
			f2f7 := &svcsdktypes.ExportToCSVOption{}
			if r.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus != nil {
				f2f7.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.ExportToCSVOption.AvailabilityStatus)
			}
			f2.ExportToCSVOption = f2f7
		}
		if r.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption != nil {
			f2f8 := &svcsdktypes.ExportWithHiddenFieldsOption{}
			if r.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus != nil {
				f2f8.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus)
			}
			f2.ExportWithHiddenFieldsOption = f2f8
		}
		if r.ko.Spec.PublishOptions.QuickSuiteActionsOption != nil {
			f2f9 := &svcsdktypes.QuickSuiteActionsOption{}
			if r.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus != nil {
				f2f9.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.QuickSuiteActionsOption.AvailabilityStatus)
			}
			f2.QuickSuiteActionsOption = f2f9
		}
		if r.ko.Spec.PublishOptions.SheetControlsOption != nil {
			f2f10 := &svcsdktypes.SheetControlsOption{}
			if r.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState != nil {
				f2f10.VisibilityState = svcsdktypes.DashboardUIState(*r.ko.Spec.PublishOptions.SheetControlsOption.VisibilityState)
			}
			f2.SheetControlsOption = f2f10
		}
		if r.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption != nil {
			f2f11 := &svcsdktypes.SheetLayoutElementMaximizationOption{}
			if r.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus != nil {
				f2f11.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus)
			}
			f2.SheetLayoutElementMaximizationOption = f2f11
		}
		if r.ko.Spec.PublishOptions.VisualAxisSortOption != nil {
			f2f12 := &svcsdktypes.VisualAxisSortOption{}
			if r.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus != nil {
				f2f12.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.VisualAxisSortOption.AvailabilityStatus)
			}
			f2.VisualAxisSortOption = f2f12
		}
		if r.ko.Spec.PublishOptions.VisualMenuOption != nil {
			f2f13 := &svcsdktypes.VisualMenuOption{}
			if r.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus != nil {
				f2f13.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.VisualMenuOption.AvailabilityStatus)
			}
			f2.VisualMenuOption = f2f13
		}
		if r.ko.Spec.PublishOptions.VisualPublishOptions != nil {
			f2f14 := &svcsdktypes.DashboardVisualPublishOptions{}
			if r.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption != nil {
				f2f14f0 := &svcsdktypes.ExportHiddenFieldsOption{}
				if r.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus != nil {
					f2f14f0.AvailabilityStatus = svcsdktypes.DashboardBehavior(*r.ko.Spec.PublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus)
				}
				f2f14.ExportHiddenFieldsOption = f2f14f0
			}
			f2.VisualPublishOptions = f2f14
		}
		res.DashboardPublishOptions = f2
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Parameters != nil {
		f4 := &svcsdktypes.Parameters{}
		if r.ko.Spec.Parameters.DateTimeParameters != nil {
			f4f0 := []svcsdktypes.DateTimeParameter{}
			for _, f4f0iter := range r.ko.Spec.Parameters.DateTimeParameters {
				f4f0elem := &svcsdktypes.DateTimeParameter{}
				if f4f0iter.Name != nil {
					f4f0elem.Name = f4f0iter.Name
				}
				if f4f0iter.Values != nil {
					f4f0elemf1 := []time.Time{}
					for _, f4f0elemf1iter := range f4f0iter.Values {
						var f4f0elemf1elem time.Time
						f4f0elemf1elem = f4f0elemf1iter.Time
						f4f0elemf1 = append(f4f0elemf1, f4f0elemf1elem)
					}
					f4f0elem.Values = f4f0elemf1
				}
				f4f0 = append(f4f0, *f4f0elem)
			}
			f4.DateTimeParameters = f4f0
		}
		if r.ko.Spec.Parameters.DecimalParameters != nil {
			f4f1 := []svcsdktypes.DecimalParameter{}
			for _, f4f1iter := range r.ko.Spec.Parameters.DecimalParameters {
				f4f1elem := &svcsdktypes.DecimalParameter{}
				if f4f1iter.Name != nil {
					f4f1elem.Name = f4f1iter.Name
				}
				if f4f1iter.Values != nil {
					f4f1elemf1 := []float64{}
					for _, f4f1elemf1iter := range f4f1iter.Values {
						var f4f1elemf1elem float64
						f4f1elemf1elem = *f4f1elemf1iter
						f4f1elemf1 = append(f4f1elemf1, f4f1elemf1elem)
					}
					f4f1elem.Values = f4f1elemf1
				}
				f4f1 = append(f4f1, *f4f1elem)
			}
			f4.DecimalParameters = f4f1
		}
		if r.ko.Spec.Parameters.IntegerParameters != nil {
			f4f2 := []svcsdktypes.IntegerParameter{}
			for _, f4f2iter := range r.ko.Spec.Parameters.IntegerParameters {
				f4f2elem := &svcsdktypes.IntegerParameter{}
				if f4f2iter.Name != nil {
					f4f2elem.Name = f4f2iter.Name
				}
				if f4f2iter.Values != nil {
					f4f2elem.Values = aws.ToInt64Slice(f4f2iter.Values)
				}
				f4f2 = append(f4f2, *f4f2elem)
			}
			f4.IntegerParameters = f4f2
		}
		if r.ko.Spec.Parameters.StringParameters != nil {
			f4f3 := []svcsdktypes.StringParameter{}
			for _, f4f3iter := range r.ko.Spec.Parameters.StringParameters {
				f4f3elem := &svcsdktypes.StringParameter{}
				if f4f3iter.Name != nil {
					f4f3elem.Name = f4f3iter.Name
				}
				if f4f3iter.Values != nil {
					f4f3elem.Values = aws.ToStringSlice(f4f3iter.Values)
				}
				f4f3 = append(f4f3, *f4f3elem)
			}
			f4.StringParameters = f4f3
		}
		res.Parameters = f4
	}
	if r.ko.Spec.SourceEntity != nil {
		f5 := &svcsdktypes.DashboardSourceEntity{}
		if r.ko.Spec.SourceEntity.SourceTemplate != nil {
			f5f0 := &svcsdktypes.DashboardSourceTemplate{}
			if r.ko.Spec.SourceEntity.SourceTemplate.ARN != nil {
				f5f0.Arn = r.ko.Spec.SourceEntity.SourceTemplate.ARN
			}
			if r.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences != nil {
				f5f0f1 := []svcsdktypes.DataSetReference{}
				for _, f5f0f1iter := range r.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences {
					f5f0f1elem := &svcsdktypes.DataSetReference{}
					if f5f0f1iter.DataSetARN != nil {
						f5f0f1elem.DataSetArn = f5f0f1iter.DataSetARN
					}
					if f5f0f1iter.DataSetPlaceholder != nil {
						f5f0f1elem.DataSetPlaceholder = f5f0f1iter.DataSetPlaceholder
					}
					f5f0f1 = append(f5f0f1, *f5f0f1elem)
				}
				f5f0.DataSetReferences = f5f0f1
			}
			f5.SourceTemplate = f5f0
		}
		res.SourceEntity = f5
	}
	if r.ko.Spec.ThemeARN != nil {
		res.ThemeArn = r.ko.Spec.ThemeARN
	}
	if r.ko.Spec.ValidationStrategy != nil {
		f7 := &svcsdktypes.ValidationStrategy{}
		if r.ko.Spec.ValidationStrategy.Mode != nil {
			f7.Mode = svcsdktypes.ValidationStrategyMode(*r.ko.Spec.ValidationStrategy.Mode)
		}
		res.ValidationStrategy = f7
	}
	if r.ko.Spec.VersionDescription != nil {
		res.VersionDescription = r.ko.Spec.VersionDescription
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteDashboardOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteDashboard(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteDashboard", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteDashboardInput, error) {
	res := &svcsdk.DeleteDashboardInput{}

	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}
	if r.ko.Spec.ID != nil {
		res.DashboardId = r.ko.Spec.ID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Dashboard,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterValueException",
		"UnsupportedUserEditionException":
		return true
	default:
		return false
	}
}
