// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package analysis

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID) {
		delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
	} else if a.ko.Spec.AWSAccountID != nil && b.ko.Spec.AWSAccountID != nil {
		if *a.ko.Spec.AWSAccountID != *b.ko.Spec.AWSAccountID {
			delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
		}
	}
	if len(a.ko.Spec.FolderARNs) != len(b.ko.Spec.FolderARNs) {
		delta.Add("Spec.FolderARNs", a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs)
	} else if len(a.ko.Spec.FolderARNs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs) {
			delta.Add("Spec.FolderARNs", a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ID, b.ko.Spec.ID) {
		delta.Add("Spec.ID", a.ko.Spec.ID, b.ko.Spec.ID)
	} else if a.ko.Spec.ID != nil && b.ko.Spec.ID != nil {
		if *a.ko.Spec.ID != *b.ko.Spec.ID {
			delta.Add("Spec.ID", a.ko.Spec.ID, b.ko.Spec.ID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Parameters, b.ko.Spec.Parameters) {
		delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
	} else if a.ko.Spec.Parameters != nil && b.ko.Spec.Parameters != nil {
		if len(a.ko.Spec.Parameters.DateTimeParameters) != len(b.ko.Spec.Parameters.DateTimeParameters) {
			delta.Add("Spec.Parameters.DateTimeParameters", a.ko.Spec.Parameters.DateTimeParameters, b.ko.Spec.Parameters.DateTimeParameters)
		} else if len(a.ko.Spec.Parameters.DateTimeParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.DateTimeParameters, b.ko.Spec.Parameters.DateTimeParameters) {
				delta.Add("Spec.Parameters.DateTimeParameters", a.ko.Spec.Parameters.DateTimeParameters, b.ko.Spec.Parameters.DateTimeParameters)
			}
		}
		if len(a.ko.Spec.Parameters.DecimalParameters) != len(b.ko.Spec.Parameters.DecimalParameters) {
			delta.Add("Spec.Parameters.DecimalParameters", a.ko.Spec.Parameters.DecimalParameters, b.ko.Spec.Parameters.DecimalParameters)
		} else if len(a.ko.Spec.Parameters.DecimalParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.DecimalParameters, b.ko.Spec.Parameters.DecimalParameters) {
				delta.Add("Spec.Parameters.DecimalParameters", a.ko.Spec.Parameters.DecimalParameters, b.ko.Spec.Parameters.DecimalParameters)
			}
		}
		if len(a.ko.Spec.Parameters.IntegerParameters) != len(b.ko.Spec.Parameters.IntegerParameters) {
			delta.Add("Spec.Parameters.IntegerParameters", a.ko.Spec.Parameters.IntegerParameters, b.ko.Spec.Parameters.IntegerParameters)
		} else if len(a.ko.Spec.Parameters.IntegerParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.IntegerParameters, b.ko.Spec.Parameters.IntegerParameters) {
				delta.Add("Spec.Parameters.IntegerParameters", a.ko.Spec.Parameters.IntegerParameters, b.ko.Spec.Parameters.IntegerParameters)
			}
		}
		if len(a.ko.Spec.Parameters.StringParameters) != len(b.ko.Spec.Parameters.StringParameters) {
			delta.Add("Spec.Parameters.StringParameters", a.ko.Spec.Parameters.StringParameters, b.ko.Spec.Parameters.StringParameters)
		} else if len(a.ko.Spec.Parameters.StringParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.StringParameters, b.ko.Spec.Parameters.StringParameters) {
				delta.Add("Spec.Parameters.StringParameters", a.ko.Spec.Parameters.StringParameters, b.ko.Spec.Parameters.StringParameters)
			}
		}
	}
	if len(a.ko.Spec.Permissions) != len(b.ko.Spec.Permissions) {
		delta.Add("Spec.Permissions", a.ko.Spec.Permissions, b.ko.Spec.Permissions)
	} else if len(a.ko.Spec.Permissions) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Permissions, b.ko.Spec.Permissions) {
			delta.Add("Spec.Permissions", a.ko.Spec.Permissions, b.ko.Spec.Permissions)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SourceEntity, b.ko.Spec.SourceEntity) {
		delta.Add("Spec.SourceEntity", a.ko.Spec.SourceEntity, b.ko.Spec.SourceEntity)
	} else if a.ko.Spec.SourceEntity != nil && b.ko.Spec.SourceEntity != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.SourceEntity.SourceTemplate, b.ko.Spec.SourceEntity.SourceTemplate) {
			delta.Add("Spec.SourceEntity.SourceTemplate", a.ko.Spec.SourceEntity.SourceTemplate, b.ko.Spec.SourceEntity.SourceTemplate)
		} else if a.ko.Spec.SourceEntity.SourceTemplate != nil && b.ko.Spec.SourceEntity.SourceTemplate != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.SourceEntity.SourceTemplate.ARN, b.ko.Spec.SourceEntity.SourceTemplate.ARN) {
				delta.Add("Spec.SourceEntity.SourceTemplate.ARN", a.ko.Spec.SourceEntity.SourceTemplate.ARN, b.ko.Spec.SourceEntity.SourceTemplate.ARN)
			} else if a.ko.Spec.SourceEntity.SourceTemplate.ARN != nil && b.ko.Spec.SourceEntity.SourceTemplate.ARN != nil {
				if *a.ko.Spec.SourceEntity.SourceTemplate.ARN != *b.ko.Spec.SourceEntity.SourceTemplate.ARN {
					delta.Add("Spec.SourceEntity.SourceTemplate.ARN", a.ko.Spec.SourceEntity.SourceTemplate.ARN, b.ko.Spec.SourceEntity.SourceTemplate.ARN)
				}
			}
			if len(a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences) != len(b.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences) {
				delta.Add("Spec.SourceEntity.SourceTemplate.DataSetReferences", a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences, b.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences)
			} else if len(a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences) > 0 {
				if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences, b.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences) {
					delta.Add("Spec.SourceEntity.SourceTemplate.DataSetReferences", a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences, b.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences)
				}
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ThemeARN, b.ko.Spec.ThemeARN) {
		delta.Add("Spec.ThemeARN", a.ko.Spec.ThemeARN, b.ko.Spec.ThemeARN)
	} else if a.ko.Spec.ThemeARN != nil && b.ko.Spec.ThemeARN != nil {
		if *a.ko.Spec.ThemeARN != *b.ko.Spec.ThemeARN {
			delta.Add("Spec.ThemeARN", a.ko.Spec.ThemeARN, b.ko.Spec.ThemeARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ValidationStrategy, b.ko.Spec.ValidationStrategy) {
		delta.Add("Spec.ValidationStrategy", a.ko.Spec.ValidationStrategy, b.ko.Spec.ValidationStrategy)
	} else if a.ko.Spec.ValidationStrategy != nil && b.ko.Spec.ValidationStrategy != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.ValidationStrategy.Mode, b.ko.Spec.ValidationStrategy.Mode) {
			delta.Add("Spec.ValidationStrategy.Mode", a.ko.Spec.ValidationStrategy.Mode, b.ko.Spec.ValidationStrategy.Mode)
		} else if a.ko.Spec.ValidationStrategy.Mode != nil && b.ko.Spec.ValidationStrategy.Mode != nil {
			if *a.ko.Spec.ValidationStrategy.Mode != *b.ko.Spec.ValidationStrategy.Mode {
				delta.Add("Spec.ValidationStrategy.Mode", a.ko.Spec.ValidationStrategy.Mode, b.ko.Spec.ValidationStrategy.Mode)
			}
		}
	}

	return delta
}
