// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package analysis

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/quicksight"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/quicksight/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/quicksight-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Analysis{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeAnalysisOutput
	resp, err = rm.sdkapi.DescribeAnalysis(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeAnalysis", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.Analysis.AnalysisId != nil {
		ko.Spec.ID = resp.Analysis.AnalysisId
	} else {
		ko.Spec.ID = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Analysis.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Analysis.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Analysis.CreatedTime != nil {
		ko.Status.CreatedTime = &metav1.Time{*resp.Analysis.CreatedTime}
	} else {
		ko.Status.CreatedTime = nil
	}
	if resp.Analysis.Errors != nil {
		f4 := []*svcapitypes.AnalysisError{}
		for _, f4iter := range resp.Analysis.Errors {
			f4elem := &svcapitypes.AnalysisError{}
			if f4iter.Message != nil {
				f4elem.Message = f4iter.Message
			}
			if f4iter.Type != "" {
				f4elem.Type = aws.String(string(f4iter.Type))
			}
			if f4iter.ViolatedEntities != nil {
				f4elemf2 := []*svcapitypes.Entity{}
				for _, f4elemf2iter := range f4iter.ViolatedEntities {
					f4elemf2elem := &svcapitypes.Entity{}
					if f4elemf2iter.Path != nil {
						f4elemf2elem.Path = f4elemf2iter.Path
					}
					f4elemf2 = append(f4elemf2, f4elemf2elem)
				}
				f4elem.ViolatedEntities = f4elemf2
			}
			f4 = append(f4, f4elem)
		}
		ko.Status.Errors = f4
	} else {
		ko.Status.Errors = nil
	}
	if resp.Analysis.LastUpdatedTime != nil {
		ko.Status.LastUpdatedTime = &metav1.Time{*resp.Analysis.LastUpdatedTime}
	} else {
		ko.Status.LastUpdatedTime = nil
	}
	if resp.Analysis.Name != nil {
		ko.Spec.Name = resp.Analysis.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Analysis.Status != "" {
		ko.Status.Status = aws.String(string(resp.Analysis.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.Analysis.ThemeArn != nil {
		ko.Spec.ThemeARN = resp.Analysis.ThemeArn
	} else {
		ko.Spec.ThemeARN = nil
	}

	rm.setStatusDefaults(ko)
	ko.Spec.Tags, err = getTags(ctx, string(*ko.Status.ACKResourceMetadata.ARN), rm.sdkapi, rm.metrics)
	if err != nil {
		return &resource{ko}, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.ID == nil || r.ko.Spec.AWSAccountID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeAnalysisInput, error) {
	res := &svcsdk.DescribeAnalysisInput{}

	if r.ko.Spec.ID != nil {
		res.AnalysisId = r.ko.Spec.ID
	}
	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateAnalysisOutput
	_ = resp
	resp, err = rm.sdkapi.CreateAnalysis(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateAnalysis", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AnalysisId != nil {
		ko.Spec.ID = resp.AnalysisId
	} else {
		ko.Spec.ID = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CreationStatus != "" {
		ko.Status.Status = aws.String(string(resp.CreationStatus))
	} else {
		ko.Status.Status = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateAnalysisInput, error) {
	res := &svcsdk.CreateAnalysisInput{}

	if r.ko.Spec.ID != nil {
		res.AnalysisId = r.ko.Spec.ID
	}
	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}
	if r.ko.Spec.FolderARNs != nil {
		res.FolderArns = aws.ToStringSlice(r.ko.Spec.FolderARNs)
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Parameters != nil {
		f4 := &svcsdktypes.Parameters{}
		if r.ko.Spec.Parameters.DateTimeParameters != nil {
			f4f0 := []svcsdktypes.DateTimeParameter{}
			for _, f4f0iter := range r.ko.Spec.Parameters.DateTimeParameters {
				f4f0elem := &svcsdktypes.DateTimeParameter{}
				if f4f0iter.Name != nil {
					f4f0elem.Name = f4f0iter.Name
				}
				if f4f0iter.Values != nil {
					f4f0elemf1 := []time.Time{}
					for _, f4f0elemf1iter := range f4f0iter.Values {
						var f4f0elemf1elem time.Time
						f4f0elemf1elem = f4f0elemf1iter.Time
						f4f0elemf1 = append(f4f0elemf1, f4f0elemf1elem)
					}
					f4f0elem.Values = f4f0elemf1
				}
				f4f0 = append(f4f0, *f4f0elem)
			}
			f4.DateTimeParameters = f4f0
		}
		if r.ko.Spec.Parameters.DecimalParameters != nil {
			f4f1 := []svcsdktypes.DecimalParameter{}
			for _, f4f1iter := range r.ko.Spec.Parameters.DecimalParameters {
				f4f1elem := &svcsdktypes.DecimalParameter{}
				if f4f1iter.Name != nil {
					f4f1elem.Name = f4f1iter.Name
				}
				if f4f1iter.Values != nil {
					f4f1elemf1 := []float64{}
					for _, f4f1elemf1iter := range f4f1iter.Values {
						var f4f1elemf1elem float64
						f4f1elemf1elem = *f4f1elemf1iter
						f4f1elemf1 = append(f4f1elemf1, f4f1elemf1elem)
					}
					f4f1elem.Values = f4f1elemf1
				}
				f4f1 = append(f4f1, *f4f1elem)
			}
			f4.DecimalParameters = f4f1
		}
		if r.ko.Spec.Parameters.IntegerParameters != nil {
			f4f2 := []svcsdktypes.IntegerParameter{}
			for _, f4f2iter := range r.ko.Spec.Parameters.IntegerParameters {
				f4f2elem := &svcsdktypes.IntegerParameter{}
				if f4f2iter.Name != nil {
					f4f2elem.Name = f4f2iter.Name
				}
				if f4f2iter.Values != nil {
					f4f2elem.Values = aws.ToInt64Slice(f4f2iter.Values)
				}
				f4f2 = append(f4f2, *f4f2elem)
			}
			f4.IntegerParameters = f4f2
		}
		if r.ko.Spec.Parameters.StringParameters != nil {
			f4f3 := []svcsdktypes.StringParameter{}
			for _, f4f3iter := range r.ko.Spec.Parameters.StringParameters {
				f4f3elem := &svcsdktypes.StringParameter{}
				if f4f3iter.Name != nil {
					f4f3elem.Name = f4f3iter.Name
				}
				if f4f3iter.Values != nil {
					f4f3elem.Values = aws.ToStringSlice(f4f3iter.Values)
				}
				f4f3 = append(f4f3, *f4f3elem)
			}
			f4.StringParameters = f4f3
		}
		res.Parameters = f4
	}
	if r.ko.Spec.Permissions != nil {
		f5 := []svcsdktypes.ResourcePermission{}
		for _, f5iter := range r.ko.Spec.Permissions {
			f5elem := &svcsdktypes.ResourcePermission{}
			if f5iter.Actions != nil {
				f5elem.Actions = aws.ToStringSlice(f5iter.Actions)
			}
			if f5iter.Principal != nil {
				f5elem.Principal = f5iter.Principal
			}
			f5 = append(f5, *f5elem)
		}
		res.Permissions = f5
	}
	if r.ko.Spec.SourceEntity != nil {
		f6 := &svcsdktypes.AnalysisSourceEntity{}
		if r.ko.Spec.SourceEntity.SourceTemplate != nil {
			f6f0 := &svcsdktypes.AnalysisSourceTemplate{}
			if r.ko.Spec.SourceEntity.SourceTemplate.ARN != nil {
				f6f0.Arn = r.ko.Spec.SourceEntity.SourceTemplate.ARN
			}
			if r.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences != nil {
				f6f0f1 := []svcsdktypes.DataSetReference{}
				for _, f6f0f1iter := range r.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences {
					f6f0f1elem := &svcsdktypes.DataSetReference{}
					if f6f0f1iter.DataSetARN != nil {
						f6f0f1elem.DataSetArn = f6f0f1iter.DataSetARN
					}
					if f6f0f1iter.DataSetPlaceholder != nil {
						f6f0f1elem.DataSetPlaceholder = f6f0f1iter.DataSetPlaceholder
					}
					f6f0f1 = append(f6f0f1, *f6f0f1elem)
				}
				f6f0.DataSetReferences = f6f0f1
			}
			f6.SourceTemplate = f6f0
		}
		res.SourceEntity = f6
	}
	if r.ko.Spec.Tags != nil {
		f7 := []svcsdktypes.Tag{}
		for _, f7iter := range r.ko.Spec.Tags {
			f7elem := &svcsdktypes.Tag{}
			if f7iter.Key != nil {
				f7elem.Key = f7iter.Key
			}
			if f7iter.Value != nil {
				f7elem.Value = f7iter.Value
			}
			f7 = append(f7, *f7elem)
		}
		res.Tags = f7
	}
	if r.ko.Spec.ThemeARN != nil {
		res.ThemeArn = r.ko.Spec.ThemeARN
	}
	if r.ko.Spec.ValidationStrategy != nil {
		f9 := &svcsdktypes.ValidationStrategy{}
		if r.ko.Spec.ValidationStrategy.Mode != nil {
			f9.Mode = svcsdktypes.ValidationStrategyMode(*r.ko.Spec.ValidationStrategy.Mode)
		}
		res.ValidationStrategy = f9
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	desired.SetStatus(latest)
	if isAnalysisUpdateReady(desired) {
		return desired, ackrequeue.NeededAfter(fmt.Errorf("resource is %s", *desired.ko.Status.Status), time.Duration(5)*time.Second)
	}

	if delta.DifferentAt("Spec.Tags") {
		arn := string(*latest.ko.Status.ACKResourceMetadata.ARN)
		err = syncTags(
			ctx,
			desired.ko.Spec.Tags, latest.ko.Spec.Tags,
			&arn, convertToOrderedACKTags, rm.sdkapi, rm.metrics,
		)
		if err != nil {
			return desired, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateAnalysisOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateAnalysis(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateAnalysis", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AnalysisId != nil {
		ko.Spec.ID = resp.AnalysisId
	} else {
		ko.Spec.ID = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.UpdateStatus != "" {
		ko.Status.Status = aws.String(string(resp.UpdateStatus))
	} else {
		ko.Status.Status = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateAnalysisInput, error) {
	res := &svcsdk.UpdateAnalysisInput{}

	if r.ko.Spec.ID != nil {
		res.AnalysisId = r.ko.Spec.ID
	}
	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Parameters != nil {
		f3 := &svcsdktypes.Parameters{}
		if r.ko.Spec.Parameters.DateTimeParameters != nil {
			f3f0 := []svcsdktypes.DateTimeParameter{}
			for _, f3f0iter := range r.ko.Spec.Parameters.DateTimeParameters {
				f3f0elem := &svcsdktypes.DateTimeParameter{}
				if f3f0iter.Name != nil {
					f3f0elem.Name = f3f0iter.Name
				}
				if f3f0iter.Values != nil {
					f3f0elemf1 := []time.Time{}
					for _, f3f0elemf1iter := range f3f0iter.Values {
						var f3f0elemf1elem time.Time
						f3f0elemf1elem = f3f0elemf1iter.Time
						f3f0elemf1 = append(f3f0elemf1, f3f0elemf1elem)
					}
					f3f0elem.Values = f3f0elemf1
				}
				f3f0 = append(f3f0, *f3f0elem)
			}
			f3.DateTimeParameters = f3f0
		}
		if r.ko.Spec.Parameters.DecimalParameters != nil {
			f3f1 := []svcsdktypes.DecimalParameter{}
			for _, f3f1iter := range r.ko.Spec.Parameters.DecimalParameters {
				f3f1elem := &svcsdktypes.DecimalParameter{}
				if f3f1iter.Name != nil {
					f3f1elem.Name = f3f1iter.Name
				}
				if f3f1iter.Values != nil {
					f3f1elemf1 := []float64{}
					for _, f3f1elemf1iter := range f3f1iter.Values {
						var f3f1elemf1elem float64
						f3f1elemf1elem = *f3f1elemf1iter
						f3f1elemf1 = append(f3f1elemf1, f3f1elemf1elem)
					}
					f3f1elem.Values = f3f1elemf1
				}
				f3f1 = append(f3f1, *f3f1elem)
			}
			f3.DecimalParameters = f3f1
		}
		if r.ko.Spec.Parameters.IntegerParameters != nil {
			f3f2 := []svcsdktypes.IntegerParameter{}
			for _, f3f2iter := range r.ko.Spec.Parameters.IntegerParameters {
				f3f2elem := &svcsdktypes.IntegerParameter{}
				if f3f2iter.Name != nil {
					f3f2elem.Name = f3f2iter.Name
				}
				if f3f2iter.Values != nil {
					f3f2elem.Values = aws.ToInt64Slice(f3f2iter.Values)
				}
				f3f2 = append(f3f2, *f3f2elem)
			}
			f3.IntegerParameters = f3f2
		}
		if r.ko.Spec.Parameters.StringParameters != nil {
			f3f3 := []svcsdktypes.StringParameter{}
			for _, f3f3iter := range r.ko.Spec.Parameters.StringParameters {
				f3f3elem := &svcsdktypes.StringParameter{}
				if f3f3iter.Name != nil {
					f3f3elem.Name = f3f3iter.Name
				}
				if f3f3iter.Values != nil {
					f3f3elem.Values = aws.ToStringSlice(f3f3iter.Values)
				}
				f3f3 = append(f3f3, *f3f3elem)
			}
			f3.StringParameters = f3f3
		}
		res.Parameters = f3
	}
	if r.ko.Spec.SourceEntity != nil {
		f4 := &svcsdktypes.AnalysisSourceEntity{}
		if r.ko.Spec.SourceEntity.SourceTemplate != nil {
			f4f0 := &svcsdktypes.AnalysisSourceTemplate{}
			if r.ko.Spec.SourceEntity.SourceTemplate.ARN != nil {
				f4f0.Arn = r.ko.Spec.SourceEntity.SourceTemplate.ARN
			}
			if r.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences != nil {
				f4f0f1 := []svcsdktypes.DataSetReference{}
				for _, f4f0f1iter := range r.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences {
					f4f0f1elem := &svcsdktypes.DataSetReference{}
					if f4f0f1iter.DataSetARN != nil {
						f4f0f1elem.DataSetArn = f4f0f1iter.DataSetARN
					}
					if f4f0f1iter.DataSetPlaceholder != nil {
						f4f0f1elem.DataSetPlaceholder = f4f0f1iter.DataSetPlaceholder
					}
					f4f0f1 = append(f4f0f1, *f4f0f1elem)
				}
				f4f0.DataSetReferences = f4f0f1
			}
			f4.SourceTemplate = f4f0
		}
		res.SourceEntity = f4
	}
	if r.ko.Spec.ThemeARN != nil {
		res.ThemeArn = r.ko.Spec.ThemeARN
	}
	if r.ko.Spec.ValidationStrategy != nil {
		f6 := &svcsdktypes.ValidationStrategy{}
		if r.ko.Spec.ValidationStrategy.Mode != nil {
			f6.Mode = svcsdktypes.ValidationStrategyMode(*r.ko.Spec.ValidationStrategy.Mode)
		}
		res.ValidationStrategy = f6
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteAnalysisOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteAnalysis(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteAnalysis", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteAnalysisInput, error) {
	res := &svcsdk.DeleteAnalysisInput{}

	if r.ko.Spec.ID != nil {
		res.AnalysisId = r.ko.Spec.ID
	}
	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Analysis,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterValueException",
		"UnsupportedUserEditionException":
		return true
	default:
		return false
	}
}
