// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package data_source

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	iamapitypes "github.com/aws-controllers-k8s/iam-controller/apis/v1alpha1"
	rdsapitypes "github.com/aws-controllers-k8s/rds-controller/apis/v1alpha1"
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrt "github.com/aws-controllers-k8s/runtime/pkg/runtime"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"
	s3apitypes "github.com/aws-controllers-k8s/s3-controller/apis/v1alpha1"
	secretsmanagerapitypes "github.com/aws-controllers-k8s/secretsmanager-controller/apis/v1alpha1"

	svcapitypes "github.com/aws-controllers-k8s/quicksight-controller/apis/v1alpha1"
)

// +kubebuilder:rbac:groups=secretsmanager.services.k8s.aws,resources=secrets,verbs=get;list
// +kubebuilder:rbac:groups=secretsmanager.services.k8s.aws,resources=secrets/status,verbs=get;list

// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles,verbs=get;list
// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles/status,verbs=get;list

// +kubebuilder:rbac:groups=rds.services.k8s.aws,resources=dbinstances,verbs=get;list
// +kubebuilder:rbac:groups=rds.services.k8s.aws,resources=dbinstances/status,verbs=get;list

// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles,verbs=get;list
// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles/status,verbs=get;list

// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles,verbs=get;list
// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles/status,verbs=get;list

// +kubebuilder:rbac:groups=s3.services.k8s.aws,resources=buckets,verbs=get;list
// +kubebuilder:rbac:groups=s3.services.k8s.aws,resources=buckets/status,verbs=get;list

// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles,verbs=get;list
// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles/status,verbs=get;list

// ClearResolvedReferences removes any reference values that were made
// concrete in the spec. It returns a copy of the input AWSResource which
// contains the original *Ref values, but none of their respective concrete
// values.
func (rm *resourceManager) ClearResolvedReferences(res acktypes.AWSResource) acktypes.AWSResource {
	ko := rm.concreteResource(res).ko.DeepCopy()

	if ko.Spec.Credentials != nil {
		if ko.Spec.Credentials.SecretRef != nil {
			ko.Spec.Credentials.SecretARN = nil
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.AthenaParameters != nil {
			if ko.Spec.Parameters.AthenaParameters.RoleRef != nil {
				ko.Spec.Parameters.AthenaParameters.RoleARN = nil
			}
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.RdsParameters != nil {
			if ko.Spec.Parameters.RdsParameters.InstanceRef != nil {
				ko.Spec.Parameters.RdsParameters.InstanceID = nil
			}
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.RedshiftParameters != nil {
			if ko.Spec.Parameters.RedshiftParameters.IAMParameters != nil {
				if ko.Spec.Parameters.RedshiftParameters.IAMParameters.RoleRef != nil {
					ko.Spec.Parameters.RedshiftParameters.IAMParameters.RoleARN = nil
				}
			}
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.S3KnowledgeBaseParameters != nil {
			if ko.Spec.Parameters.S3KnowledgeBaseParameters.RoleRef != nil {
				ko.Spec.Parameters.S3KnowledgeBaseParameters.RoleARN = nil
			}
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.S3Parameters != nil {
			if ko.Spec.Parameters.S3Parameters.ManifestFileLocation != nil {
				if ko.Spec.Parameters.S3Parameters.ManifestFileLocation.BucketRef != nil {
					ko.Spec.Parameters.S3Parameters.ManifestFileLocation.Bucket = nil
				}
			}
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.S3Parameters != nil {
			if ko.Spec.Parameters.S3Parameters.RoleRef != nil {
				ko.Spec.Parameters.S3Parameters.RoleARN = nil
			}
		}
	}

	return &resource{ko}
}

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve those
// reference field(s) into their respective target field(s). It returns a
// copy of the input AWSResource with resolved reference(s), a boolean which
// is set to true if the resource contains any references (regardless of if
// they are resolved successfully) and an error if the passed AWSResource's
// reference field(s) could not be resolved.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, bool, error) {
	ko := rm.concreteResource(res).ko

	resourceHasReferences := false
	err := validateReferenceFields(ko)
	if fieldHasReferences, err := rm.resolveReferenceForCredentials_SecretARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForParameters_AthenaParameters_RoleARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForParameters_RdsParameters_InstanceID(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForParameters_RedshiftParameters_IAMParameters_RoleARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForParameters_S3KnowledgeBaseParameters_RoleARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForParameters_S3Parameters_ManifestFileLocation_Bucket(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForParameters_S3Parameters_RoleARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	return &resource{ko}, resourceHasReferences, err
}

// validateReferenceFields validates the reference field and corresponding
// identifier field.
func validateReferenceFields(ko *svcapitypes.DataSource) error {

	if ko.Spec.Credentials != nil {
		if ko.Spec.Credentials.SecretRef != nil && ko.Spec.Credentials.SecretARN != nil {
			return ackerr.ResourceReferenceAndIDNotSupportedFor("Credentials.SecretARN", "Credentials.SecretRef")
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.AthenaParameters != nil {
			if ko.Spec.Parameters.AthenaParameters.RoleRef != nil && ko.Spec.Parameters.AthenaParameters.RoleARN != nil {
				return ackerr.ResourceReferenceAndIDNotSupportedFor("Parameters.AthenaParameters.RoleARN", "Parameters.AthenaParameters.RoleRef")
			}
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.RdsParameters != nil {
			if ko.Spec.Parameters.RdsParameters.InstanceRef != nil && ko.Spec.Parameters.RdsParameters.InstanceID != nil {
				return ackerr.ResourceReferenceAndIDNotSupportedFor("Parameters.RdsParameters.InstanceID", "Parameters.RdsParameters.InstanceRef")
			}
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.RedshiftParameters != nil {
			if ko.Spec.Parameters.RedshiftParameters.IAMParameters != nil {
				if ko.Spec.Parameters.RedshiftParameters.IAMParameters.RoleRef != nil && ko.Spec.Parameters.RedshiftParameters.IAMParameters.RoleARN != nil {
					return ackerr.ResourceReferenceAndIDNotSupportedFor("Parameters.RedshiftParameters.IAMParameters.RoleARN", "Parameters.RedshiftParameters.IAMParameters.RoleRef")
				}
			}
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.S3KnowledgeBaseParameters != nil {
			if ko.Spec.Parameters.S3KnowledgeBaseParameters.RoleRef != nil && ko.Spec.Parameters.S3KnowledgeBaseParameters.RoleARN != nil {
				return ackerr.ResourceReferenceAndIDNotSupportedFor("Parameters.S3KnowledgeBaseParameters.RoleARN", "Parameters.S3KnowledgeBaseParameters.RoleRef")
			}
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.S3Parameters != nil {
			if ko.Spec.Parameters.S3Parameters.ManifestFileLocation != nil {
				if ko.Spec.Parameters.S3Parameters.ManifestFileLocation.BucketRef != nil && ko.Spec.Parameters.S3Parameters.ManifestFileLocation.Bucket != nil {
					return ackerr.ResourceReferenceAndIDNotSupportedFor("Parameters.S3Parameters.ManifestFileLocation.Bucket", "Parameters.S3Parameters.ManifestFileLocation.BucketRef")
				}
			}
		}
	}

	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.S3Parameters != nil {
			if ko.Spec.Parameters.S3Parameters.RoleRef != nil && ko.Spec.Parameters.S3Parameters.RoleARN != nil {
				return ackerr.ResourceReferenceAndIDNotSupportedFor("Parameters.S3Parameters.RoleARN", "Parameters.S3Parameters.RoleRef")
			}
		}
	}
	return nil
}

// resolveReferenceForCredentials_SecretARN reads the resource referenced
// from Credentials.SecretRef field and sets the Credentials.SecretARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForCredentials_SecretARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.DataSource,
) (hasReferences bool, err error) {
	if ko.Spec.Credentials != nil {
		if ko.Spec.Credentials.SecretRef != nil && ko.Spec.Credentials.SecretRef.From != nil {
			hasReferences = true
			arr := ko.Spec.Credentials.SecretRef.From
			if arr.Name == nil || *arr.Name == "" {
				return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Credentials.SecretRef")
			}
			namespace, err := ackrt.ResolveCrossNamespaceReference(
				ctx,
				rm.cfg.EnableCrossNamespace,
				&ko.Status.Conditions,
				ackrt.CrossNamespaceRefKindResource,
				ko.ObjectMeta.GetNamespace(),
				arr.Namespace,
				*arr.Name,
			)
			if err != nil {
				return hasReferences, err
			}
			obj := &secretsmanagerapitypes.Secret{}
			if err := getReferencedResourceState_Secret(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
				return hasReferences, err
			}
			ko.Spec.Credentials.SecretARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_Secret looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Secret(
	ctx context.Context,
	apiReader client.Reader,
	obj *secretsmanagerapitypes.Secret,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Secret",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Secret",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Secret",
			namespace, name)
	}
	if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Secret",
			namespace, name,
			"Status.ACKResourceMetadata.ARN")
	}
	return nil
}

// resolveReferenceForParameters_AthenaParameters_RoleARN reads the resource referenced
// from Parameters.AthenaParameters.RoleRef field and sets the Parameters.AthenaParameters.RoleARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForParameters_AthenaParameters_RoleARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.DataSource,
) (hasReferences bool, err error) {
	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.AthenaParameters != nil {
			if ko.Spec.Parameters.AthenaParameters.RoleRef != nil && ko.Spec.Parameters.AthenaParameters.RoleRef.From != nil {
				hasReferences = true
				arr := ko.Spec.Parameters.AthenaParameters.RoleRef.From
				if arr.Name == nil || *arr.Name == "" {
					return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Parameters.AthenaParameters.RoleRef")
				}
				namespace, err := ackrt.ResolveCrossNamespaceReference(
					ctx,
					rm.cfg.EnableCrossNamespace,
					&ko.Status.Conditions,
					ackrt.CrossNamespaceRefKindResource,
					ko.ObjectMeta.GetNamespace(),
					arr.Namespace,
					*arr.Name,
				)
				if err != nil {
					return hasReferences, err
				}
				obj := &iamapitypes.Role{}
				if err := getReferencedResourceState_Role(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
					return hasReferences, err
				}
				ko.Spec.Parameters.AthenaParameters.RoleARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
			}
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_Role looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Role(
	ctx context.Context,
	apiReader client.Reader,
	obj *iamapitypes.Role,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Role",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Role",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Role",
			namespace, name)
	}
	if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Role",
			namespace, name,
			"Status.ACKResourceMetadata.ARN")
	}
	return nil
}

// resolveReferenceForParameters_RdsParameters_InstanceID reads the resource referenced
// from Parameters.RdsParameters.InstanceRef field and sets the Parameters.RdsParameters.InstanceID
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForParameters_RdsParameters_InstanceID(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.DataSource,
) (hasReferences bool, err error) {
	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.RdsParameters != nil {
			if ko.Spec.Parameters.RdsParameters.InstanceRef != nil && ko.Spec.Parameters.RdsParameters.InstanceRef.From != nil {
				hasReferences = true
				arr := ko.Spec.Parameters.RdsParameters.InstanceRef.From
				if arr.Name == nil || *arr.Name == "" {
					return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Parameters.RdsParameters.InstanceRef")
				}
				namespace, err := ackrt.ResolveCrossNamespaceReference(
					ctx,
					rm.cfg.EnableCrossNamespace,
					&ko.Status.Conditions,
					ackrt.CrossNamespaceRefKindResource,
					ko.ObjectMeta.GetNamespace(),
					arr.Namespace,
					*arr.Name,
				)
				if err != nil {
					return hasReferences, err
				}
				obj := &rdsapitypes.DBInstance{}
				if err := getReferencedResourceState_DBInstance(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
					return hasReferences, err
				}
				ko.Spec.Parameters.RdsParameters.InstanceID = (*string)(obj.Spec.DBInstanceIdentifier)
			}
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_DBInstance looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_DBInstance(
	ctx context.Context,
	apiReader client.Reader,
	obj *rdsapitypes.DBInstance,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"DBInstance",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"DBInstance",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"DBInstance",
			namespace, name)
	}
	if obj.Spec.DBInstanceIdentifier == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"DBInstance",
			namespace, name,
			"Spec.DBInstanceIdentifier")
	}
	return nil
}

// resolveReferenceForParameters_RedshiftParameters_IAMParameters_RoleARN reads the resource referenced
// from Parameters.RedshiftParameters.IAMParameters.RoleRef field and sets the Parameters.RedshiftParameters.IAMParameters.RoleARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForParameters_RedshiftParameters_IAMParameters_RoleARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.DataSource,
) (hasReferences bool, err error) {
	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.RedshiftParameters != nil {
			if ko.Spec.Parameters.RedshiftParameters.IAMParameters != nil {
				if ko.Spec.Parameters.RedshiftParameters.IAMParameters.RoleRef != nil && ko.Spec.Parameters.RedshiftParameters.IAMParameters.RoleRef.From != nil {
					hasReferences = true
					arr := ko.Spec.Parameters.RedshiftParameters.IAMParameters.RoleRef.From
					if arr.Name == nil || *arr.Name == "" {
						return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Parameters.RedshiftParameters.IAMParameters.RoleRef")
					}
					namespace, err := ackrt.ResolveCrossNamespaceReference(
						ctx,
						rm.cfg.EnableCrossNamespace,
						&ko.Status.Conditions,
						ackrt.CrossNamespaceRefKindResource,
						ko.ObjectMeta.GetNamespace(),
						arr.Namespace,
						*arr.Name,
					)
					if err != nil {
						return hasReferences, err
					}
					obj := &iamapitypes.Role{}
					if err := getReferencedResourceState_Role(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
						return hasReferences, err
					}
					ko.Spec.Parameters.RedshiftParameters.IAMParameters.RoleARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
				}
			}
		}
	}

	return hasReferences, nil
}

// resolveReferenceForParameters_S3KnowledgeBaseParameters_RoleARN reads the resource referenced
// from Parameters.S3KnowledgeBaseParameters.RoleRef field and sets the Parameters.S3KnowledgeBaseParameters.RoleARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForParameters_S3KnowledgeBaseParameters_RoleARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.DataSource,
) (hasReferences bool, err error) {
	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.S3KnowledgeBaseParameters != nil {
			if ko.Spec.Parameters.S3KnowledgeBaseParameters.RoleRef != nil && ko.Spec.Parameters.S3KnowledgeBaseParameters.RoleRef.From != nil {
				hasReferences = true
				arr := ko.Spec.Parameters.S3KnowledgeBaseParameters.RoleRef.From
				if arr.Name == nil || *arr.Name == "" {
					return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Parameters.S3KnowledgeBaseParameters.RoleRef")
				}
				namespace, err := ackrt.ResolveCrossNamespaceReference(
					ctx,
					rm.cfg.EnableCrossNamespace,
					&ko.Status.Conditions,
					ackrt.CrossNamespaceRefKindResource,
					ko.ObjectMeta.GetNamespace(),
					arr.Namespace,
					*arr.Name,
				)
				if err != nil {
					return hasReferences, err
				}
				obj := &iamapitypes.Role{}
				if err := getReferencedResourceState_Role(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
					return hasReferences, err
				}
				ko.Spec.Parameters.S3KnowledgeBaseParameters.RoleARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
			}
		}
	}

	return hasReferences, nil
}

// resolveReferenceForParameters_S3Parameters_ManifestFileLocation_Bucket reads the resource referenced
// from Parameters.S3Parameters.ManifestFileLocation.BucketRef field and sets the Parameters.S3Parameters.ManifestFileLocation.Bucket
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForParameters_S3Parameters_ManifestFileLocation_Bucket(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.DataSource,
) (hasReferences bool, err error) {
	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.S3Parameters != nil {
			if ko.Spec.Parameters.S3Parameters.ManifestFileLocation != nil {
				if ko.Spec.Parameters.S3Parameters.ManifestFileLocation.BucketRef != nil && ko.Spec.Parameters.S3Parameters.ManifestFileLocation.BucketRef.From != nil {
					hasReferences = true
					arr := ko.Spec.Parameters.S3Parameters.ManifestFileLocation.BucketRef.From
					if arr.Name == nil || *arr.Name == "" {
						return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Parameters.S3Parameters.ManifestFileLocation.BucketRef")
					}
					namespace, err := ackrt.ResolveCrossNamespaceReference(
						ctx,
						rm.cfg.EnableCrossNamespace,
						&ko.Status.Conditions,
						ackrt.CrossNamespaceRefKindResource,
						ko.ObjectMeta.GetNamespace(),
						arr.Namespace,
						*arr.Name,
					)
					if err != nil {
						return hasReferences, err
					}
					obj := &s3apitypes.Bucket{}
					if err := getReferencedResourceState_Bucket(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
						return hasReferences, err
					}
					ko.Spec.Parameters.S3Parameters.ManifestFileLocation.Bucket = (*string)(obj.Spec.Name)
				}
			}
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_Bucket looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Bucket(
	ctx context.Context,
	apiReader client.Reader,
	obj *s3apitypes.Bucket,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Bucket",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Bucket",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Bucket",
			namespace, name)
	}
	if obj.Spec.Name == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Bucket",
			namespace, name,
			"Spec.Name")
	}
	return nil
}

// resolveReferenceForParameters_S3Parameters_RoleARN reads the resource referenced
// from Parameters.S3Parameters.RoleRef field and sets the Parameters.S3Parameters.RoleARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForParameters_S3Parameters_RoleARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.DataSource,
) (hasReferences bool, err error) {
	if ko.Spec.Parameters != nil {
		if ko.Spec.Parameters.S3Parameters != nil {
			if ko.Spec.Parameters.S3Parameters.RoleRef != nil && ko.Spec.Parameters.S3Parameters.RoleRef.From != nil {
				hasReferences = true
				arr := ko.Spec.Parameters.S3Parameters.RoleRef.From
				if arr.Name == nil || *arr.Name == "" {
					return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Parameters.S3Parameters.RoleRef")
				}
				namespace, err := ackrt.ResolveCrossNamespaceReference(
					ctx,
					rm.cfg.EnableCrossNamespace,
					&ko.Status.Conditions,
					ackrt.CrossNamespaceRefKindResource,
					ko.ObjectMeta.GetNamespace(),
					arr.Namespace,
					*arr.Name,
				)
				if err != nil {
					return hasReferences, err
				}
				obj := &iamapitypes.Role{}
				if err := getReferencedResourceState_Role(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
					return hasReferences, err
				}
				ko.Spec.Parameters.S3Parameters.RoleARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
			}
		}
	}

	return hasReferences, nil
}
